### ISSUE TITLE
Cursor is a missing glyph when inputting command in windows terminal 

### ISSUE THREAD

**Issue by wh7** [gsass1/NTop#31]
![cursor](https://user-images.githubusercontent.com/45503569/86730787-78d7f100-c061-11ea-9d52-8381e937419a.gif)

**Comment by dd86k** [comment]
I'm seeing something similar with Cascadia Code but not with Consolas, both tested under ConsoleZ.

Culprit seems to be line 1771 in ntop.c: `ConPutc(219);`

219 is simply an extended ascii code and thus an unknown glyph to most modern fonts. Commenting the line or the block gets rid of the unknown glyph.

@gsass1 meet me behind school at 5
