### ISSUE TITLE
Add option to display cpu loads like in htop. 

### ISSUE THREAD

**Issue by kotenok2000** [gsass1/NTop#45]
![Снимок экрана (126)](https://user-images.githubusercontent.com/8822292/152271446-da512d35-e31b-4c4c-a58b-7f9095ef1d41.png)

![Снимок экрана (127)](https://user-images.githubusercontent.com/8822292/152271423-e3673a8c-a36f-4351-9a17-4969d3b61af0.png)

**Comment by gsass1** [comment]
https://github.com/gsass1/NTop/issues/9
